//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyAuctionAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.CurrentBids = new HashSet<CurrentBid>();
        }
    
        public int AuctionID { get; set; }
        public int ToyID { get; set; }
        public Nullable<int> WinningBidderID { get; set; }
        public Nullable<decimal> WinningBid { get; set; }
        public Nullable<System.DateTime> AuctionStart { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
    
        public virtual Toy Toy { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentBid> CurrentBids { get; set; }
    }
}
