//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyAuctionAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentBid
    {
        public int BidderID { get; set; }
        public int AuctionID { get; set; }
        public System.DateTime BidTime { get; set; }
        public decimal Bid { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual User User { get; set; }
    }
}
